### ISSUE TITLE
bridge doesn't automatically start MDRP (preferences not being saved)

### ISSUE THREAD

**Issue by RoguedBear** [jojo2357/MDRP-MusicBee-Bridge#2]
When setting the MDRP.exe path in plugin settings in musicbee UI, after i get a check mark when i hit save and restart musicbee MDRP isn't opened. Manually openening MDRP, it detects the bridge (it says that in the console).

When i opened the preference page, the plugin settings were back to default. empty path, imagepack standard and "Close MDRP on mb" checked.

If i enter the path and check auto start again and hit save and then open the preferences page again its back to default again.
As if the preferences are not being saved.

Though after manually starting MDRP and then i close mb, MDRP is also closed.

Would be glad to provide any logs if possible.
<br>

--
(Great job on the v1.6.0 updates and the musicbee plugin btw 🥳 )

**Comment by jojo2357** [comment]
I have this issue replicated, although I don't know how I missed it 🤔. In the meantime, you can use the backdoor settings way. 
1. In the top right theres 3 rectangles in a square with a tooltip of `Configure Layout`. Click that
2. Arrange Panels
3. Under available elements, select `mdrp bridge` 
4. Apply/save.
5. Now there should be something extra on your layout with the title `MDRP Status`. Click the image and a settings window should pop up. 
6. Hopefully that works for now while I get a patch out for this

Also, glad to see you again and I always appreciate your thorough issue reports :)

**Comment by RoguedBear** [comment]
I tried the new dll, and the settings are being saved but here's the weird thing.

First i tried to save via the preferences menu in mb... didn't save
Then i tried the panel layout workaround you suggested. The settings were saved in that plugin menu, persisted an application restart and was also reflected in the mb preferences page.

Now i tried changing the settings via the mb preferences menu, and now settings are being saved from there as well. 😄

i guess that solves it ¯\\_(ツ)_/¯

(Also i love the programmer image pack :>)

**Comment by RoguedBear** [comment]
Having more packs would be such a cool nice little addition!! 
I appreciate you both bringing out new features to this project :v:
