### ISSUE TITLE
Settings just revert back to what they were

### ISSUE THREAD

**Issue by Kenzie1000000** [jojo2357/MDRP-MusicBee-Bridge#3]
![image](https://user-images.githubusercontent.com/89376969/162567725-ce63e565-9178-4ae1-8f10-b47119a692a2.png)
no matter what I do the settings just revert to this

**Comment by jojo2357** [comment]
Could you elaborate on what you did exactly to cause this problem so i can replicate it?

**Comment by RoguedBear** [comment]
i believe this is what #2 was.

When i reinstalled windows on my computer and installed musicbee, the same issue happened with me.

If i remember correctly (this was back in January), settings weren't being saved (as described in #2 and here) so I followed the workarounds suggested [there](https://github.com/jojo2357/MDRP-MusicBee-Bridge/issues/2#issuecomment-942401753) and after fiddling with "backdoor settings" way, preferences started to being saved again as described in my comment https://github.com/jojo2357/MDRP-MusicBee-Bridge/issues/2#issuecomment-943514647

**Comment by Kenzie1000000** [comment]
> Could you elaborate on what you did exactly to cause this problem so i can replicate it?

I'll uncheck "Close MDRP on MB close" press apply and save and then I go back to the settings and it's back to being checked, I've only just installed it and have tried reinstalling it but nothing has worked, I don't have this problem with any other plugin

**Comment by jojo2357** [comment]
Well I have to make an update for MDRP 1.7.0 so I will address this when I get the chance. In the meantime, try the backdoor way that RoguedBear mentioned, and hopefully that works out for you

**Comment by Kenzie1000000** [comment]
> Well I have to make an update for MDRP 1.7.0 so I will address this when I get the chance. In the meantime, try the backdoor way that RoguedBear mentioned, and hopefully that works out for you

Yeah the backdoor way worked thanks, thanks for making the plugin btw
